### ISSUE TITLE
Unacceptable docking poses when docking DNA and small molecule

### ISSUE THREAD

**Issue by supernova4869** [PKUGaoGroup/DSDP#11]
I tried to dock the small molecule to DNA, but I met the unacceptable docking results, where the small molecule conflicts with the DNA sidechain. Could you please check the reason? Thank you. Here is my command:
```
./DSDP_redocking/DSDP --protein receptor.pdbqt --ligand GTV.pdbqt --box_min -9.59603 2.856407 -7.972692 --box_max 63.713564 76.166001 65.336902
```
The related files have been uploaded: 
[dock.zip](https://github.com/PKUGaoGroup/DSDP/files/14792444/dock.zip)

**Comment by PKUGaoGroup** [comment]
I delete the Fe atom in  receptor.pdbqt, the problem solved. In addition, it is better to decrease the box size. The present  box is too big.

**Comment by supernova4869** [comment]
> I delete the Fe atom in receptor.pdbqt, the problem solved. In addition, it is better to decrease the box size. The present box is too big.

Thank you. Is there any way to dock with Fe atom?
