### ISSUE TITLE
Wish to add help infomation or documentation to DSDP

### ISSUE THREAD

**Issue by supernova4869** [PKUGaoGroup/DSDP#2]
It maybe better to add some help infomation when directly running DSDP (or with `-h`), instead of meaningless "wrong parameters" hint. 
Meanwhile, if the documentation of using DSDP for blind docking and/or redocking tasks was provided, it would be more convinent for users to do their own studies. Although the original paper of DSDP has been published on JCIM, it focused on the principle and implementation of DSDP, while it would be better if there is a documentation that pays more attentation on the usage of DSDP. Thank you!

**Comment by HCAya** [comment]
Thanks for your issue. By now we implemented `--help, -h` and a new argument parser. Please check the new version.

**Comment by supernova4869** [comment]
Thanks for the new arguments! I have also made Pull Request with some modifications to the DSDP_blind_docking.py, so that the blind docking study will not be limited to the DSDP project.

**Comment by HCAya** [comment]
We recently found that changing to C++17 (to meet the argparse library) might cause potential problems. So I changed to another library and turned back to C++11 standard. The arguments are unchanged. Please see the new version. Thanks.

**Comment by supernova4869** [comment]
Thanks a lot for updating! But I met a compilation problem with CLI11. It printed:
```
nvcc -o main_SingleRun_SitePointStart.o -c main_SingleRun_SitePointStart.cu -arch=sm_60 -rdc=true -lcudadevrt -lcufft --use_fast_math -O4 -std=c++11 -lgomp
CLI11.hpp(1090): warning #20236-D: pragma "diag_suppress" is deprecated, use "nv_diag_suppress" instead

CLI11.hpp(1094): warning #20236-D: pragma "diag_default" is deprecated, use "nv_diag_default" instead

CLI11.hpp(1090): warning #20236-D: pragma "diag_suppress" is deprecated, use "nv_diag_suppress" instead

CLI11.hpp(1094): warning #20236-D: pragma "diag_default" is deprecated, use "nv_diag_default" instead

/usr/include/c++/11/bits/std_function.h:435:145: 错误：参数包未能在‘...’中被展开：
  435 |         function(_Functor&& __f)
      |                                                                                                                                                 ^ 
/usr/include/c++/11/bits/std_function.h:435:145: 附注：       ‘_ArgTypes’
/usr/include/c++/11/bits/std_function.h:530:146: 错误：参数包未能在‘...’中被展开：
  530 |         operator=(_Functor&& __f)
      |                                                                                                                                                  ^ 
/usr/include/c++/11/bits/std_function.h:530:146: 附注：       ‘_ArgTypes’
make: *** [Makefile:17：main_SingleRun_SitePointStart.o] 错误 1
```
Seems that CLI11 somewhere not fit my environment:
gcc 11.3.1
cuda 11.6 (but pytorch 11.7)

**Comment by supernova4869** [comment]
Oh, I found that pytorch does not support cuda 11.6, but I also used mindspore which constraints the cuda version to 11.0 or 11.6. Seems that they are not compatible.

**Comment by HCAya** [comment]
Hi, there seems to be some problem with compiler versions. 
I test compilation with cuda 11.6/11.7 + gcc 10.5/11.4 and they all passed.
But cuda 11.0 is incompatible with gcc > 9. Please check about the actual cuda-toolkit version in your environment. If needed, you could install cuda-toolkit individually and set it to the system path. Hope you have solved that problem.

**Comment by supernova4869** [comment]
Deeply grateful for the answer! Now I understand the relationship between pytorch and cuda toolkit. I built both cuda 11.6 and cuda 11.8 so that DSDP and mindspore could both be normally used. Thank you!
