### ISSUE TITLE
Cannot see why DSDP_blind_docking fails

### ISSUE THREAD

**Issue by ryan-pauling-ai** [PKUGaoGroup/DSDP#4]
The script seems to have made the site ok, during the step of running DSDP/DSDP_blind_docking/DSDP it prints no logs, no output, and just prints. 
drug discovery >>>
drug discovery !!!
Time: 1235371.410671
Running DSDP/DSDP_blind_docking/DSDP seperate for one of the ligands just prints this, again no log or output file
size of protein mesh 288000000
/content/DSDP/Ex1_site.npy
note that it did not print the time, like a sucessful run would have. Not sure what is going on. 
[ExProblemLigs.zip](https://github.com/PKUGaoGroup/DSDP/files/12822247/ExProblemLigs.zip)

**Comment by PKUGaoGroup** [comment]
The output and log documents of DSDP are printed in the "results" file. Please see /results/DSDP_dataset/docking_results.

**Comment by ryan-pauling-ai** [comment]
Yes I can see the results if I use your provided dataset. If I use my own files, like the ones attached to the previous message, it does not work. It does create the surface but it does not dock at all and does not tell me what the problem is. Does not write an output nor a log. My request is that the program tells what the problem is. Thanks

**Comment by PKUGaoGroup** [comment]
The input files of DSDP are suggested to be generated by AutodockTools, and DSDP used this format to recognize the input pdbqt. I tried to change your input format and got the output and log. Please see the attachment, and run it using the *_new.pdbqt. 
Thanks~
[ExProblemLigs.zip](https://github.com/PKUGaoGroup/DSDP/files/12855822/ExProblemLigs.zip)

**Comment by ryan-pauling-ai** [comment]
Thank you, I found the problem as well before reading this. Namely I was sending in a file that had several modes already and it would not support multiple models for input. Thanks again for the response.
