### ISSUE TITLE
Segmentation fault when docking huge MOF-DNA with small ligand

### ISSUE THREAD

**Issue by supernova4869** [PKUGaoGroup/DSDP#5]
I tried to dock a big molecule MIL53-Fe-aptamer complex and a small oxytetracycline molecule with DSDP redocking toolkit, which reported segmentation fault with no other information. Wishing that the reason could be found, thank you! The command is:
```
/path/to/DSDP/DSDP_redocking/DSDP --ligand OTC.mol2 --protein MIL_apt_3p_oct.pdbqt --box_min 78.868044 61.657419 86.501169 --box_max 116.995082 99.784457 124.628207 --out 3p_oct.pdbqt --log 3p_oct.log
```
The related files are as below:
[files.zip](https://github.com/PKUGaoGroup/DSDP/files/12878113/files.zip)

**Comment by HCAya** [comment]
Please provide a .pdbqt formatted ligand input. The current DSDP_redocking version does not support mol2.

**Comment by supernova4869** [comment]
Oh, sorry. I forgot the ligand should also be treated as pdbqt.
