### ISSUE TITLE
Why is OpenBabel removed from README?

### ISSUE THREAD

**Issue by supernova4869** [PKUGaoGroup/DSDP#6]
Should the pdbqt file only be created by AutoDock Tools? Is there any important difference between the pdbqt files derived from AutoDock Tools and OpenBabel? If there is some important reasons, I may try to construct some useful tools for generating pdbqt input files needed by DSDP, in order to avoid using unconvinent AutoDock Tools software.

**Comment by pikakolendo02** [comment]
I found openbabel necessary when using blind docking:
```
Traceback (most recent call last):
  File "/home/pika/DSDP/DSDP_blind_docking.py", line 3, in <module>
    from openbabel import pybel
ModuleNotFoundError: No module named 'openbabel'
```
so openbabel should be mentioned in requirements or DSDP.yml.

**Comment by PKUGaoGroup** [comment]
> I found openbabel necessary when using blind docking:
> 
> ```
> Traceback (most recent call last):
>   File "/home/pika/DSDP/DSDP_blind_docking.py", line 3, in <module>
>     from openbabel import pybel
> ModuleNotFoundError: No module named 'openbabel'
> ```
> 
> so openbabel should be mentioned in requirements or DSDP.yml.

Thanks for your suggestion. Please check the environment has been set successfully, openbabel was included in the DSDP.yml ( - openbabel=3.1.1=py38hf4b5c11_1).

**Comment by Rhylan2333** [comment]
> Should the pdbqt file only be created by AutoDock Tools? Is there any important difference between the pdbqt files derived from AutoDock Tools and OpenBabel? pdbqt文件应该只由AutoDock Tools创建吗？从AutoDock Tools和OpenBabel派生的pdbqt文件之间有什么重要的区别吗？ If there is some important reasons, I may try to construct some useful tools for generating pdbqt input files needed by DSDP, in order to avoid using unconvinent AutoDock Tools software.如果有一些重要的原因，我可能会尝试构建一些有用的工具来生成DSDP所需的pdbqt输入文件，以避免使用不方便的AutoDock Tools软件。



> Should the pdbqt file only be created by AutoDock Tools? Is there any important difference between the pdbqt files derived from AutoDock Tools and OpenBabel? pdbqt文件应该只由AutoDock Tools创建吗？从AutoDock Tools和OpenBabel派生的pdbqt文件之间有什么重要的区别吗？ If there is some important reasons, I may try to construct some useful tools for generating pdbqt input files needed by DSDP, in order to avoid using unconvinent AutoDock Tools software.如果有一些重要的原因，我可能会尝试构建一些有用的工具来生成DSDP所需的pdbqt输入文件，以避免使用不方便的AutoDock Tools软件。

My personal experience with OpenBabel has shown that the conformations of small molecule ligands generated by the program can sometimes result in unusual bond angles. I once used OpenBabel to generate a sharp angle bond, which was quite unreasonable for my ligand molecule, and even worse, it altered the conformation of my input file. Therefore, I prefer to use [MGLTools (aliases for AutoDock Tools)](https://ccsb.scripps.edu/mgltools/downloads/), as it produces output that almost perfectly matches the input file's conformation. [This is a brief tutorial](https://bioinformaticsreview.com/20200716/prepare-receptor-and-ligand-files-for-docking-using-python-scripts/).

Additionally, if you need to convert 2D plane-formatted small molecules to 3D solid constructs, I recommend [MarvinSketch](https://docs.chemaxon.com/display/lts-europium/marvinsketch-downloads.md) and [Gypsum-DL](https://jcheminf.biomedcentral.com/articles/10.1186/s13321-019-0358-3). Their output results are generally satisfactory.

**Comment by Rhylan2333** [comment]
> Should the pdbqt file only be created by AutoDock Tools? Is there any important difference between the pdbqt files derived from AutoDock Tools and OpenBabel? If there is some important reasons, I may try to construct some useful tools for generating pdbqt input files needed by DSDP, in order to avoid using unconvinent AutoDock Tools software.

Through my personal experience using OpenBabel, I found that the conformations it generates for small molecule ligands can sometimes result in unusual bond angles. While I never used it to convert files from .pdb to .pdbqt formats, I once employed OpenBabel to convert 2D plane-formatted (SDF) small molecules to 3D stereochemical structures (mol2). However, it produced a sharply angled bond that was quite unreasonable for my ligand molecule. I've heard that OpenBabel is faster, but I won't use it unless I have to.

While converting between .pdb and .pdbqt formats is a "3D to 3D" task, I prefer to use MGLTools (also known as AutoDock Tools, ADT) for this purpose. It produces outputs that almost perfectly match the input conformations. The results from CLI version (MGLTools) consist with those generated through its GUI version (ADT). [Here is a brief tutorial](https://bioinformaticsreview.com/20200716/prepare-receptor-and-ligand-files-for-docking-using-python-scripts/), I like MGLTools.

Additionally, if you need to deal woth a "2D to 3D" tast, I recommend [MarvinSketch](https://docs.chemaxon.com/display/lts-europium/marvinsketch-downloads.md) and [Gypsum-DL](https://jcheminf.biomedcentral.com/articles/10.1186/s13321-019-0358-3). Their outputs are generally satisfactory.

**Comment by Rhylan2333** [comment]
> Should the pdbqt file only be created by AutoDock Tools? Is there any important difference between the pdbqt files derived from AutoDock Tools and OpenBabel? If there is some important reasons, I may try to construct some useful tools for generating pdbqt input files needed by DSDP, in order to avoid using unconvinent AutoDock Tools software.

Through my personal experience using OpenBabel, I found that the conformations it generates for small molecule ligands can sometimes result in unusual bond angles. While I never used it to convert files from .pdb to .pdbqt formats, I once employed OpenBabel to convert 2D plane-formatted (SDF) small molecules to 3D stereochemical structures (mol2). However, it produced a sharply angled bond that was quite unreasonable for my ligand molecule. I've heard that OpenBabel is faster, but I won't use it unless I have to😕.

While converting between .pdb and .pdbqt formats is a "3D to 3D" task, I prefer to use MGLTools (also known as AutoDock Tools, ADT) for this purpose. It produces outputs that almost perfectly match the input conformations. The results from its CLI version ([ADFRsuit](https://ccsb.scripps.edu/adfr/downloads/)) consist with those generated through its GUI version (ADT/MGLTools). [Here is a brief tutorial actually for ADFRsuit](https://bioinformaticsreview.com/20200716/prepare-receptor-and-ligand-files-for-docking-using-python-scripts/), I like ADFR more🙂.

Additionally, if you need to deal woth a "2D to 3D" tast, I recommend [MarvinSketch](https://docs.chemaxon.com/display/lts-europium/marvinsketch-downloads.md) and [Gypsum-DL](https://jcheminf.biomedcentral.com/articles/10.1186/s13321-019-0358-3). Their outputs are generally satisfactory.

**Comment by supernova4869** [comment]
> > Should the pdbqt file only be created by AutoDock Tools? Is there any important difference between the pdbqt files derived from AutoDock Tools and OpenBabel? If there is some important reasons, I may try to construct some useful tools for generating pdbqt input files needed by DSDP, in order to avoid using unconvinent AutoDock Tools software.
> 
> Through my personal experience using OpenBabel, I found that the conformations it generates for small molecule ligands can sometimes result in unusual bond angles. While I never used it to convert files from .pdb to .pdbqt formats, I once employed OpenBabel to convert 2D plane-formatted (SDF) small molecules to 3D stereochemical structures (mol2). However, it produced a sharply angled bond that was quite unreasonable for my ligand molecule. I've heard that OpenBabel is faster, but I won't use it unless I have to😕.
> 
> While converting between .pdb and .pdbqt formats is a "3D to 3D" task, I prefer to use MGLTools (also known as AutoDock Tools, ADT) for this purpose. It produces outputs that almost perfectly match the input conformations. The results from its CLI version ([ADFRsuit](https://ccsb.scripps.edu/adfr/downloads/)) consist with those generated through its GUI version (ADT/MGLTools). [Here is a brief tutorial actually for ADFRsuit](https://bioinformaticsreview.com/20200716/prepare-receptor-and-ligand-files-for-docking-using-python-scripts/), I like ADFR more🙂.
> 
> Additionally, if you need to deal woth a "2D to 3D" tast, I recommend [MarvinSketch](https://docs.chemaxon.com/display/lts-europium/marvinsketch-downloads.md) and [Gypsum-DL](https://jcheminf.biomedcentral.com/articles/10.1186/s13321-019-0358-3). Their outputs are generally satisfactory.

Thank you for your detailed reply. Additionally, I also found that obabel sometimes treats the protein with branches, which does not match the semi-flexible docking algorithm, and may also cause the vina error (but no error when using DSDP).

**Comment by Rhylan2333** [comment]
Received!
